#!/usr/bin/env escript
%% -*- erlang -*-
%%! -sname rebar_to_bazel
-mode(compile).

main([MetadataFile]) ->
    {ok, Metadata} = file:consult(MetadataFile),

    Map = maps:map(
        fun
            (_, [{_, _} | _] = V) ->
                proplists:to_map(V);
            (_, V) ->
                V
        end,
        proplists:to_map(Metadata)),

    Json = to_json(Map),

    io:format("~s~n", [Json]).

to_json(M) when is_map(M) ->
    Pairs = [to_json(K) ++ ": " ++ to_json(V) || {K, V} <- maps:to_list(M)],
    "{" ++ string:join(Pairs, ",") ++ "}";
to_json(L) when is_list(L) ->
    Items = lists:map(fun to_json/1, L),
    "[" ++ string:join(Items, ",") ++ "]";
to_json(S) when is_binary(S) ->
    "\"" ++ binary_to_list(S) ++ "\"".
